=== koubevo/xml-coursework/schema/sem.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
    elementFormDefault="qualified" 
    targetNamespace="urn:x-koubevo:schemas:restaurace" 
    xmlns="urn:x-koubevo:schemas:restaurace">
    
    <xs:element name="recenze" type="recenzeType">
        <xs:key name="restauraceKey">
            <xs:selector xpath="restaurace"/>
            <xs:field xpath="id"/>
        </xs:key>
        <xs:keyref name="topJidloRef" refer="restauraceKey">
            <xs:selector xpath="restaurace/top_jidlo"/>
            <xs:field xpath="@ref_restaurace_id"/>
        </xs:keyref>
    </xs:element>
        
    <xs:complexType name="recenzeType">
        <xs:sequence>
            <xs:element name="restaurace" type="restauraceType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="restauraceType">
        <xs:sequence>
            <xs:element name="id" type="idType"/>
            <xs:element name="nazev" type="nazevType"/>
            <xs:element name="popis" type="popisType"/>
            <xs:element name="majitel" type="majitelType"/>
            <xs:element name="mesto" type="mestoType"/>
            <xs:element name="stat" type="statType"/>
            <xs:element name="oteviraci_doba" type="oteviraciDobaType"/>
            <xs:element name="menu" type="menuType"/>
            <xs:element name="kategorie" type="kategorieType" maxOccurs="unbounded"/>
            <xs:element name="hodnoceni" type="hodnoceniType"/>
            <xs:element name="top_jidlo" type="topJidloType"/>
            <xs:element name="cena_osoba" type="cenaType"/>
            <xs:element name="platba_kartou" type="platbaKartouType"/>
            <xs:element name="qerko" type="qerkoType"/>
            <xs:element name="poledni_menu" type="poledniMenuType"/>
            <xs:element name="datum_navstevy" type="datumNavstevyType"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:simpleType name="idType">
        <xs:restriction base="xs:integer">
            <xs:minExclusive value="100000"/>
            <xs:maxExclusive value="999999"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="nazevType">
        <xs:restriction base="strng"/>
    </xs:simpleType>
    
    <xs:simpleType name="popisType">
        <xs:restriction base="strng"/>
    </xs:simpleType>
    
    <xs:simpleType name="majitelType">
        <xs:restriction base="xs:string">
            <xs:minLength value="0"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="mestoType">
        <xs:restriction base="strng"/>
    </xs:simpleType>
    
    <xs:simpleType name="statType">
        <xs:restriction base="strng"/>
    </xs:simpleType>
    
    <xs:complexType name="oteviraciDobaType">
        <xs:sequence>
            <xs:element name="pondeli" type="casType" minOccurs="0" maxOccurs="1"/>
            <xs:element name="utery" type="casType" minOccurs="0" maxOccurs="1"/>
            <xs:element name="streda" type="casType" minOccurs="0" maxOccurs="1"/>
            <xs:element name="ctvrtek" type="casType" minOccurs="0" maxOccurs="1"/>
            <xs:element name="patek" type="casType" minOccurs="0" maxOccurs="1"/>
            <xs:element name="sobota" type="casType" minOccurs="0" maxOccurs="1"/>
            <xs:element name="nedele" type="casType" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="casType">
        <xs:sequence>
            <xs:element name="od" type="xs:time" minOccurs="0"/>
            <xs:element name="do" type="xs:time" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="zavreno" type="xs:boolean" use="optional"/>
    </xs:complexType>
    
    <xs:simpleType name="menuType">
        <xs:restriction base="xs:anyURI"/>
    </xs:simpleType>
    
    <xs:simpleType name="kategorieType">
        <xs:restriction base="strng"/>
    </xs:simpleType>
    
    <xs:complexType name="hodnoceniType">
        <xs:sequence>
            <xs:element name="slovni" type="slovniType"/>
            <xs:element name="hvezdicky" type="hvezdickyType"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:simpleType name="slovniType">
        <xs:restriction base="strng"/>
    </xs:simpleType>
    
    <xs:complexType name="hvezdickyType">
        <xs:sequence>
            <xs:element name="misto" type="cisloHvezdicekType"/>
            <xs:element name="obsluha" type="cisloHvezdicekType"/>
            <xs:element name="jidlo" type="cisloHvezdicekType"/>
            <xs:element name="finalni" type="cisloHvezdicekType"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:simpleType name="cisloHvezdicekType">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="5"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="topJidloType">
        <xs:sequence>
            <xs:element name="nazev" type="nazevType"/>
            <xs:element name="cena" type="cenaType"/>
            <xs:element name="foto" type="fotoType"/>
        </xs:sequence>
        <xs:attribute name="ref_restaurace_id" type="idType" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="cenaType">
        <xs:simpleContent>
            <xs:extension base="xs:integer">
                <xs:attribute name="mena" use="required">
                    <xs:simpleType>
                        <xs:restriction base="strng">
                            <xs:enumeration value="USD"/>
                            <xs:enumeration value="CZK"/>
                            <xs:enumeration value="EUR"/>
                            <xs:enumeration value="GBP"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    
    
    <xs:simpleType name="fotoType">
        <xs:restriction base="strng">
            <xs:pattern value="[\w,\s-]+\.(jpg|jpeg|png)"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="platbaKartouType">
        <xs:restriction base="strng">
            <xs:enumeration value="ano"/>
            <xs:enumeration value="ne"/>
            <xs:enumeration value="někdy"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="qerkoType">
        <xs:restriction base="strng">
            <xs:enumeration value="ano"/>
            <xs:enumeration value="ne"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="poledniMenuType">
        <xs:restriction base="strng">
            <xs:enumeration value="každý den"/>
            <xs:enumeration value="pracovní dny"/>
            <xs:enumeration value="víkendy"/>
            <xs:enumeration value="ne"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="datumNavstevyType">
        <xs:restriction base="xs:date"/>
    </xs:simpleType>
    
    <xs:simpleType name="strng">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>
    
</xs:schema>

=== koubevo/xml-coursework/sem.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="sem.xsd"?>
<recenze xmlns="urn:x-koubevo:schemas:restaurace" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:x-koubevo:schemas:restaurace sem.xsd">
    <restaurace>
        <id>152698</id>
        <nazev>Brambory Na Pankráci</nazev>
        <popis>Podnik se nachází v Praze na Pankráci a kromě výborného YUMMY jídla a originálního bramborového konceptu nabízí i krásný interiér a otevřenou kuchyň.</popis>
        <majitel></majitel>
        <mesto>Praha</mesto>
        <stat>Česko</stat>
        <oteviraci_doba>
            <pondeli>
                <od>11:00:00</od>
                <do>23:00:00</do>
            </pondeli>
            <utery>
                <od>10:00:00</od>
                <do>22:00:00</do>
            </utery>
            <streda zavreno="true"/>
            <ctvrtek>
                <od>11:00:00</od>
                <do>23:00:00</do>
            </ctvrtek>
            <patek>
                <od>11:00:00</od>
                <do>00:00:00</do>
            </patek>
            <sobota>
                <od>12:00:00</od>
                <do>00:00:00</do>
            </sobota>
            <nedele>
                <od>12:00:00</od>
                <do>21:00:00</do>
            </nedele>
        </oteviraci_doba>
        <menu>https://www.bramborynapankraci.cz/menu/</menu>
        <kategorie>Degustace</kategorie>
        <kategorie>Brambory</kategorie>
        <hodnoceni>
            <slovni>Jídlo a obsulha skvělé. Interiér vypadá hezky, jen se připravte na hluk. Pokud půjdete okolo, určitě doporučujeme navštívit!</slovni>
            <hvezdicky>
                <misto>4</misto>
                <obsluha>5</obsluha>
                <jidlo>5</jidlo>
                <finalni>4.5</finalni>
            </hvezdicky>
        </hodnoceni>
        <top_jidlo>
            <nazev>Hovězí degustace</nazev>
            <cena mena="czk">458</cena>
            <foto>brambory.jpeg</foto>
        </top_jidlo>
        <cena_osoba mena="czk">500</cena_osoba>
        <platba_kartou>ano</platba_kartou>
        <qerko>ano</qerko>
        <poledni_menu>každý den</poledni_menu>
        <datum_navstevy>2024-10-10</datum_navstevy>
    </restaurace>
    <restaurace>
        <id>203457</id>
        <nazev>Pizza Paradise</nazev>
        <popis>Italská restaurace s širokou nabídkou pizz, těstovin a salátů, která se nachází v  Klášterci nad Ohří.</popis>
        <majitel>Luigi Rossi</majitel>
        <mesto> Klášterec nad Ohří</mesto>
        <stat>Česko</stat>
        <oteviraci_doba>
            <pondeli>
                <od>11:00:00</od>
                <do>22:00:00</do>
            </pondeli>
            <utery>
                <od>11:00:00</od>
                <do>22:00:00</do>
            </utery>
            <streda>
                <od>11:00:00</od>
                <do>22:00:00</do>
            </streda>
            <ctvrtek>
                <od>11:00:00</od>
                <do>22:00:00</do>
            </ctvrtek>
            <patek>
                <od>11:00:00</od>
                <do>23:00:00</do>
            </patek>
            <sobota>
                <od>12:00:00</od>
                <do>23:00:00</do>
            </sobota>
            <nedele>
                <od>12:00:00</od>
                <do>22:00:00</do>
            </nedele>
        </oteviraci_doba>
        <menu>https://www.pizzaparadise.cz</menu>
        <kategorie>Pizza</kategorie>
        <kategorie>Italská kuchyně</kategorie>
        <hodnoceni>
            <slovni>Pizza je výborná, obsluha přátelská. Doporučujeme vyzkoušet jejich domácí tiramisu!</slovni>
            <hvezdicky>
                <misto>5</misto>
                <obsluha>4</obsluha>
                <jidlo>5</jidlo>
                <finalni>4.5</finalni>
            </hvezdicky>
        </hodnoceni>
        <top_jidlo>
            <nazev>Margarita</nazev>
            <cena mena="czk">150</cena>
            <foto>pizza.jpeg</foto>
        </top_jidlo>
        <cena_osoba mena="czk">300</cena_osoba>
        <platba_kartou>ano</platba_kartou>
        <qerko>ne</qerko>
        <poledni_menu>pracovní dny</poledni_menu>
        <datum_navstevy>2024-11-20</datum_navstevy>
    </restaurace>
</recenze>

=== koubevo/xml-coursework/xml_samples/sem.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="../schema/sem.xsd"?>
<?xml-model href="../schema/sem.sch" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<recenze xmlns="urn:x-koubevo:schemas:restaurace" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:x-koubevo:schemas:restaurace ../schema/sem.xsd">
    <restaurace>
        <id>152698</id>
        <nazev>Brambory Na Pankráci</nazev>
        <popis>Podnik se nachází v Praze na Pankráci a kromě výborného YUMMY jídla a originálního bramborového konceptu nabízí i krásný interiér a otevřenou kuchyň.</popis>
        <majitel></majitel>
        <mesto>Praha</mesto>
        <stat>Česko</stat>
        <oteviraci_doba>
            <pondeli>
                <od>11:00:00</od>
                <do>23:00:00</do>
            </pondeli>
            <utery>
                <od>10:00:00</od>
                <do>22:00:00</do>
            </utery>
            <streda zavreno="true"/>
            <ctvrtek>
                <od>11:00:00</od>
                <do>23:00:00</do>
            </ctvrtek>
            <patek>
                <od>11:00:00</od>
                <do>00:00:00</do>
            </patek>
            <sobota>
                <od>12:00:00</od>
                <do>00:00:00</do>
            </sobota>
            <nedele>
                <od>12:00:00</od>
                <do>21:00:00</do>
            </nedele>
        </oteviraci_doba>
        <menu>https://www.bramborynapankraci.cz/menu/</menu>
        <kategorie>Degustace</kategorie>
        <kategorie>Brambory</kategorie>
        <hodnoceni>
            <slovni>Jídlo a obsulha skvělé. Interiér vypadá hezky, jen se připravte na hluk. Pokud půjdete okolo, určitě doporučujeme navštívit!</slovni>
            <hvezdicky>
                <misto>4</misto>
                <obsluha>5</obsluha>
                <jidlo>5</jidlo>
                <finalni>4.5</finalni>
            </hvezdicky>
        </hodnoceni>
        <top_jidlo ref_restaurace_id="152698">
            <nazev>Hovězí degustace</nazev>
            <cena mena="CZK">458</cena>
            <foto>brambory.jpg</foto>
        </top_jidlo>
        <cena_osoba mena="CZK">500</cena_osoba>
        <platba_kartou>ano</platba_kartou>
        <qerko>ano</qerko>
        <poledni_menu>každý den</poledni_menu>
        <datum_navstevy>2024-10-10</datum_navstevy>
    </restaurace>
    <restaurace>
        <id>152699</id>
        <nazev>Pizza Paradise</nazev>
        <popis>Italská restaurace s širokou nabídkou pizz, těstovin a salátů, která se nachází v  Klášterci nad Ohří.</popis>
        <majitel>Luigi Rossi</majitel>
        <mesto>Klášterec nad Ohří</mesto>
        <stat>Česko</stat>
        <oteviraci_doba>
            <pondeli>
                <od>11:00:00</od>
                <do>22:00:00</do>
            </pondeli>
            <utery>
                <od>11:00:00</od>
                <do>22:00:00</do>
            </utery>
            <streda>
                <od>11:00:00</od>
                <do>22:00:00</do>
            </streda>
            <ctvrtek>
                <od>11:00:00</od>
                <do>22:00:00</do>
            </ctvrtek>
            <patek>
                <od>11:00:00</od>
                <do>23:00:00</do>
            </patek>
            <sobota>
                <od>12:00:00</od>
                <do>23:00:00</do>
            </sobota>
            <nedele zavreno="true">
            </nedele>
        </oteviraci_doba>
        <menu>https://www.pizzaparadise.cz</menu>
        <kategorie>Pizza</kategorie>
        <kategorie>Italská kuchyně</kategorie>
        <hodnoceni>
            <slovni>Pizza je výborná, obsluha přátelská. Doporučujeme vyzkoušet jejich domácí tiramisu!</slovni>
            <hvezdicky>
                <misto>2</misto>
                <obsluha>3</obsluha>
                <jidlo>4</jidlo>
                <finalni>3</finalni>
            </hvezdicky>
        </hodnoceni>
        <top_jidlo ref_restaurace_id="152699">
            <nazev>Margarita</nazev>
            <cena mena="CZK">150</cena>
            <foto>pizza.jpg</foto>
        </top_jidlo>
        <cena_osoba mena="CZK">300</cena_osoba>
        <platba_kartou>ano</platba_kartou>
        <qerko>ne</qerko>
        <poledni_menu>pracovní dny</poledni_menu>
        <datum_navstevy>2024-11-20</datum_navstevy>
    </restaurace>
    <restaurace>
        <id>152700</id>
        <nazev>Café Imperial</nazev>
        <popis>Ikonická restaurace v Praze, známá pro svůj krásný interiér ve stylu art deco.</popis>
        <majitel>Zdeněk Polreich</majitel>
        <mesto>Praha</mesto>
        <stat>Česko</stat>
        <oteviraci_doba>
            <pondeli>
                <od>07:00:00</od>
                <do>23:00:00</do>
            </pondeli>
            <utery>
                <od>07:00:00</od>
                <do>23:00:00</do>
            </utery>
            <streda>
                <od>07:00:00</od>
                <do>23:00:00</do>
            </streda>
            <ctvrtek>
                <od>07:00:00</od>
                <do>23:00:00</do>
            </ctvrtek>
            <patek>
                <od>07:00:00</od>
                <do>23:00:00</do>
            </patek>
            <sobota>
                <od>07:00:00</od>
                <do>23:00:00</do>
            </sobota>
            <nedele>
                <od>07:00:00</od>
                <do>23:00:00</do>
            </nedele>
        </oteviraci_doba>
        <menu>https://www.cafeimperial.cz/jidelni-listek-2/</menu>
        <kategorie>Světová kuchyně</kategorie>
        <kategorie>Luxusní restaurace</kategorie>
        <hodnoceni>
            <slovni>Předkrmy dobré, hlavní chody skvělé, dezerty dokonalé. Doporučujeme rezervaci!</slovni>
            <hvezdicky>
                <misto>5</misto>
                <obsluha>5</obsluha>
                <jidlo>5</jidlo>
                <finalni>5</finalni>
            </hvezdicky>
        </hodnoceni>
        <top_jidlo ref_restaurace_id="152700">
            <nazev>Čokoládový fondant</nazev>
            <cena mena="CZK">120</cena>
            <foto>imperial.jpg</foto>
        </top_jidlo>
        <cena_osoba mena="CZK">1000</cena_osoba>
        <platba_kartou>ano</platba_kartou>
        <qerko>ne</qerko>
        <poledni_menu>každý den</poledni_menu>
        <datum_navstevy>2024-12-05</datum_navstevy>
    </restaurace>
    <restaurace>
        <id>152701</id>
        <nazev>Goldies</nazev>
        <popis>Nejlepší burgery v Praze. Sedněte na Hlaváku do vlaku, za 4 hoďky jste v Berlíně a šup na Goldies!</popis>
        <majitel>Anna Müller</majitel>
        <mesto>Berlín</mesto>
        <stat>Německo</stat>
        <oteviraci_doba>
            <pondeli>
                <od>12:00:00</od>
                <do>22:00:00</do>
            </pondeli>
            <utery>
                <od>12:00:00</od>
                <do>22:00:00</do>
            </utery>
            <streda>
                <od>12:00:00</od>
                <do>22:00:00</do>
            </streda>
            <ctvrtek>
                <od>12:00:00</od>
                <do>22:00:00</do>
            </ctvrtek>
            <patek>
                <od>12:00:00</od>
                <do>00:00:00</do>
            </patek>
            <sobota>
                <od>12:00:00</od>
                <do>00:00:00</do>
            </sobota>
            <nedele>
                <od>12:00:00</od>
                <do>22:00:00</do>
            </nedele>
        </oteviraci_doba>
        <menu>https://www.goldies-smashburger.de/#Menu</menu>
        <kategorie>Burgery</kategorie>
        <hodnoceni>
            <slovni>Nejlepší smashburgery, co jsme kdy zkusili! Místo je nonstop plné, ale obsaluha je super rychlá.</slovni>
            <hvezdicky>
                <misto>4</misto>
                <obsluha>5</obsluha>
                <jidlo>5</jidlo>
                <finalni>5</finalni>
            </hvezdicky>
        </hodnoceni>
        <top_jidlo ref_restaurace_id="152701">
            <nazev>Super Smash BLT Double</nazev>
            <cena mena="EUR">25</cena>
            <foto>goldies.jpg</foto>
        </top_jidlo>
        <cena_osoba mena="EUR">25</cena_osoba>
        <platba_kartou>ano</platba_kartou>
        <qerko>ne</qerko>
        <poledni_menu>ne</poledni_menu>
        <datum_navstevy>2024-06-06</datum_navstevy>
    </restaurace>
</recenze>
